[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pymatdet"
version = "1.0.3"
authors = [
  { name="Viren Tanti", email="virentanti16@gmail.com" },
]
description = "This is a module which can be used for performing matrix operations"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Virentanti/MatrixObject"
"Bug Tracker" = "https://github.com/Virentanti/MatrixObject/issues"